// convex/forecasts.ts
// Moving-average energy forecasts — generated by cron, read by dashboard.

import { v } from "convex/values";
import { internalMutation, query } from "./_generated/server";
import { internal } from "./_generated/api";

const HOURS_BACK       = 7 * 24;  // 7 days of history for the moving average
const FORECAST_HOURS   = 24;      // predict next 24 hours
const INTERVAL_SECONDS = 5;       // telemetry resolution

// ── Internal: cron entry point — run forecasts for all online hubs ────────
export const generateForAllHubs = internalMutation({
  args: {},
  handler: async (ctx) => {
    const hubs = await ctx.db.query("hubs").collect();
    for (const hub of hubs) {
      if (hub.status === "online") {
        await ctx.runMutation(internal.forecasts.generate, {
          hubId:  hub._id,
          userId: hub.userId,
        });
      }
    }
  },
});

// ── Internal: generate and store a 24-hour moving-average forecast ─────────
// Called by the daily cron for each active hub.
export const generate = internalMutation({
  args: {
    hubId:  v.id("hubs"),
    userId: v.id("users"),
  },
  handler: async (ctx, args) => {
    const nowSec = Math.floor(Date.now() / 1000);
    const fromSec = nowSec - HOURS_BACK * 3600;

    // Pull recent hub readings
    const readings = await ctx.db
      .query("hubReadings")
      .withIndex("by_hub_time", (q: any) =>
        q.eq("hubId", args.hubId).gte("timestamp", fromSec)
      )
      .collect();

    if (readings.length < 12) return;  // not enough data

    // Bucket readings by hour-of-day (0–23) to compute average load per hour
    const hourBuckets: number[][] = Array.from({ length: 24 }, () => []);
    for (const r of readings) {
      // WAT = UTC+1
      const watHour = Math.floor((r.timestamp + 3600) / 3600) % 24;
      hourBuckets[watHour].push(r.totalPowerW);
    }

    // Average and std-dev per hour
    const hourStats = hourBuckets.map((samples) => {
      if (samples.length === 0) return { mean: 0, std: 0 };
      const mean = samples.reduce((s, v) => s + v, 0) / samples.length;
      const variance =
        samples.reduce((s, v) => s + Math.pow(v - mean, 2), 0) / samples.length;
      return { mean, std: Math.sqrt(variance) };
    });

    // Build 24 forecast data points, one per hour starting from the next full hour
    const nextHourSec = (Math.floor(nowSec / 3600) + 1) * 3600;
    const dataPoints = Array.from({ length: FORECAST_HOURS }, (_, i) => {
      const ts    = nextHourSec + i * 3600;
      const watH  = Math.floor((ts + 3600) / 3600) % 24;
      const stats = hourStats[watH];
      // Convert avg watt-hours to kWh (one interval = 1 hour here)
      const kwhPerHour = (stats.mean * INTERVAL_SECONDS) / 3600 / 1000;
      const stdKwh     = (stats.std  * INTERVAL_SECONDS) / 3600 / 1000;
      return {
        timestamp:      ts,
        predictedKwh:   Math.round(kwhPerHour * 1000) / 1000,
        confidenceLow:  Math.round(Math.max(0, kwhPerHour - stdKwh) * 1000) / 1000,
        confidenceHigh: Math.round((kwhPerHour + stdKwh) * 1000) / 1000,
      };
    });

    await ctx.db.insert("forecasts", {
      hubId:        args.hubId,
      userId:       args.userId,
      generatedAt:  Date.now(),
      forecastType: "moving_average",
      dataPoints,
    });
  },
});

// ── Public: get the latest forecast for a hub ────────────────────────────
export const getLatest = query({
  args: { hubId: v.id("hubs") },
  handler: async (ctx, args) => {
    const identity = await ctx.auth.getUserIdentity();
    if (!identity) return null;
    const user = await ctx.db
      .query("users")
      .withIndex("by_clerk_id", (q: any) => q.eq("clerkId", identity.subject))
      .unique();
    if (!user) return null;
    const hub = await ctx.db.get(args.hubId);
    if (!hub || hub.userId !== user._id) return null;
    return await ctx.db
      .query("forecasts")
      .withIndex("by_hub_time", (q: any) => q.eq("hubId", args.hubId))
      .order("desc")
      .first();
  },
});

// ── Public: get forecast history for a hub ───────────────────────────────
export const getHistory = query({
  args: {
    hubId: v.id("hubs"),
    limit: v.optional(v.number()),
  },
  handler: async (ctx, args) => {
    const identity = await ctx.auth.getUserIdentity();
    if (!identity) return [];
    const user = await ctx.db
      .query("users")
      .withIndex("by_clerk_id", (q: any) => q.eq("clerkId", identity.subject))
      .unique();
    if (!user) return [];
    const hub = await ctx.db.get(args.hubId);
    if (!hub || hub.userId !== user._id) return [];
    return await ctx.db
      .query("forecasts")
      .withIndex("by_hub_time", (q: any) => q.eq("hubId", args.hubId))
      .order("desc")
      .take(args.limit ?? 7);
  },
});
